# Generated by Django 5.0.3 on 2024-04-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.TextField(default='default_value'),
        ),
    ]
