# Generated by Django 5.0.3 on 2024-04-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0002_rename_subject_contact_mobile_contact_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
                ('Country', models.TextField()),
                ('Pincode', models.CharField(max_length=30)),
            ],
        ),
    ]
