# Generated by Django 5.0.3 on 2024-04-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='Phone',
        ),
    ]
