# Generated by Django 5.0.3 on 2024-04-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0004_rename_phone_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='State',
            field=models.CharField(max_length=50),
        ),
    ]
