# Generated by Django 5.0.3 on 2024-04-05 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0005_alter_orders_city_alter_orders_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Price',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='ProductName',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
