# Generated by Django 5.0.3 on 2024-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical', '0006_orders_price_orders_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='product',
            field=models.CharField(max_length=30),
        ),
    ]
